// <auto-generated />
namespace HappyLife.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addingdiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdiet));
        
        string IMigrationMetadata.Id
        {
            get { return "202101071543183_adding-diet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
